const { createClient } = require("@supabase/supabase-js");
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
require("dotenv").config();

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  throw new Error("Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
}

const supabase = createClient(supabaseUrl, supabaseKey);

const TABLES = [
  { name: "records", orderBy: "id" },
  { name: "wishlist", orderBy: "id" },
  { name: "discography_targets", orderBy: "release_id" },
  { name: "nfc_tags", orderBy: "created_at" },
  { name: "listens", orderBy: "listened_at" },
];

const PAGE_SIZE = 1000;

async function fetchAllRows(table) {
  const rows = [];
  let offset = 0;
  let hasMore = true;

  while (hasMore) {
    const { data, error } = await supabase
      .from(table.name)
      .select("*")
      .order(table.orderBy)
      .range(offset, offset + PAGE_SIZE - 1);

    if (error) throw new Error(`Failed to fetch ${table.name}: ${error.message}`);
    if (!data || data.length === 0) {
      hasMore = false;
    } else {
      rows.push(...data);
      offset += PAGE_SIZE;
      if (data.length < PAGE_SIZE) hasMore = false;
    }
  }

  return rows;
}

function generateRestoreSql(tableData) {
  const lines = [
    "-- Restore script generated by backup system",
    `-- Generated at: ${new Date().toISOString()}`,
    "",
    "BEGIN;",
    "",
    "-- Delete in reverse dependency order",
    "DELETE FROM listens;",
    "DELETE FROM nfc_tags;",
    "DELETE FROM discography_targets;",
    "DELETE FROM wishlist;",
    "DELETE FROM records;",
    "",
  ];

  for (const table of TABLES) {
    const rows = tableData.get(table.name);
    if (!rows || rows.length === 0) continue;

    lines.push(`-- ${table.name} (${rows.length} rows)`);
    for (const row of rows) {
      const columns = Object.keys(row);
      const values = columns.map((col) => {
        const val = row[col];
        if (val === null) return "NULL";
        if (typeof val === "number") return String(val);
        if (typeof val === "boolean") return val ? "TRUE" : "FALSE";
        return `'${String(val).replace(/'/g, "''")}'`;
      });
      lines.push(
        `INSERT INTO ${table.name} (${columns.join(", ")}) VALUES (${values.join(", ")}) ON CONFLICT DO NOTHING;`
      );
    }
    lines.push("");
  }

  lines.push("COMMIT;");
  return lines.join("\n");
}

async function backup() {
  const args = process.argv.slice(2);
  const pushFlag = args.includes("--push");
  const dirIndex = args.indexOf("--dir");
  const today = new Date().toISOString().split("T")[0];
  const outputDir =
    dirIndex !== -1
      ? path.resolve(args[dirIndex + 1])
      : path.join(__dirname, "..", "backups", today);

  console.log("Starting backup...");

  const tableData = new Map();
  const counts = {};
  let totalRows = 0;

  for (const table of TABLES) {
    const rows = await fetchAllRows(table);
    tableData.set(table.name, rows);
    counts[table.name] = rows.length;
    totalRows += rows.length;
    console.log(`  ${table.name}: ${rows.length} rows`);
  }

  // Write files
  const dataDir = path.join(outputDir, "data");
  fs.mkdirSync(dataDir, { recursive: true });

  for (const [tableName, rows] of tableData) {
    fs.writeFileSync(
      path.join(dataDir, `${tableName}.json`),
      JSON.stringify(rows, null, 2)
    );
  }

  fs.writeFileSync(
    path.join(outputDir, "restore.sql"),
    generateRestoreSql(tableData)
  );

  const manifest = {
    timestamp: new Date().toISOString(),
    tables: counts,
    totalRows,
  };
  fs.writeFileSync(
    path.join(outputDir, "manifest.json"),
    JSON.stringify(manifest, null, 2)
  );

  console.log(`\nBackup written to: ${outputDir}`);
  console.log(`Total: ${totalRows} rows`);

  // Push to GitHub if requested
  if (pushFlag) {
    const backupRepo = process.env.BACKUP_REPO;
    const githubToken = process.env.BACKUP_GITHUB_TOKEN;

    if (!backupRepo || !githubToken) {
      throw new Error("Missing BACKUP_REPO or BACKUP_GITHUB_TOKEN env vars for --push");
    }

    const tmpDir = path.join(require("os").tmpdir(), `record-backup-${Date.now()}`);
    const repoUrl = `https://${githubToken}@github.com/${backupRepo}.git`;

    console.log("\nPushing to GitHub...");
    try {
      execSync(`git clone --depth 1 ${repoUrl} "${tmpDir}"`, { stdio: "pipe" });

      // Copy backup files to repo
      const destDataDir = path.join(tmpDir, "data");
      fs.mkdirSync(destDataDir, { recursive: true });

      for (const [tableName] of tableData) {
        fs.copyFileSync(
          path.join(dataDir, `${tableName}.json`),
          path.join(destDataDir, `${tableName}.json`)
        );
      }
      fs.copyFileSync(
        path.join(outputDir, "restore.sql"),
        path.join(tmpDir, "restore.sql")
      );
      fs.copyFileSync(
        path.join(outputDir, "manifest.json"),
        path.join(tmpDir, "manifest.json")
      );

      const countSummary = Object.entries(counts)
        .map(([t, c]) => `${t}: ${c}`)
        .join(", ");
      const commitMsg = `Backup ${manifest.timestamp} \u2014 ${totalRows} rows (${countSummary})`;

      execSync("git add -A", { cwd: tmpDir, stdio: "pipe" });
      execSync(`git commit -m "${commitMsg}"`, { cwd: tmpDir, stdio: "pipe" });
      execSync("git push", { cwd: tmpDir, stdio: "pipe" });

      console.log("Pushed successfully!");

      // Cleanup
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch (err) {
      // Cleanup on error
      if (fs.existsSync(tmpDir)) {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
      throw err;
    }
  }
}

backup().catch((err) => {
  console.error("Backup failed:", err.message);
  process.exit(1);
});
