import { createClient } from "@supabase/supabase-js";

export const config = { maxDuration: 60 };

interface TableConfig {
  name: string;
  orderBy: string;
}

const TABLES: TableConfig[] = [
  { name: "records", orderBy: "id" },
  { name: "wishlist", orderBy: "id" },
  { name: "discography_targets", orderBy: "release_id" },
  { name: "nfc_tags", orderBy: "created_at" },
  { name: "listens", orderBy: "listened_at" },
];

const PAGE_SIZE = 1000;

async function fetchAllRows(
  supabase: ReturnType<typeof createClient>,
  table: TableConfig
): Promise<{ rows: Record<string, unknown>[]; count: number }> {
  const rows: Record<string, unknown>[] = [];
  let offset = 0;
  let hasMore = true;

  while (hasMore) {
    const { data, error } = await supabase
      .from(table.name)
      .select("*")
      .order(table.orderBy)
      .range(offset, offset + PAGE_SIZE - 1);

    if (error) throw new Error(`Failed to fetch ${table.name}: ${error.message}`);
    if (!data || data.length === 0) {
      hasMore = false;
    } else {
      rows.push(...data);
      offset += PAGE_SIZE;
      if (data.length < PAGE_SIZE) hasMore = false;
    }
  }

  return { rows, count: rows.length };
}

function generateRestoreSql(tableData: Map<string, Record<string, unknown>[]>): string {
  const lines: string[] = [
    "-- Restore script generated by backup system",
    `-- Generated at: ${new Date().toISOString()}`,
    "",
    "BEGIN;",
    "",
    "-- Delete in reverse dependency order",
    "DELETE FROM listens;",
    "DELETE FROM nfc_tags;",
    "DELETE FROM discography_targets;",
    "DELETE FROM wishlist;",
    "DELETE FROM records;",
    "",
  ];

  // Insert in dependency order
  for (const table of TABLES) {
    const rows = tableData.get(table.name);
    if (!rows || rows.length === 0) continue;

    lines.push(`-- ${table.name} (${rows.length} rows)`);
    for (const row of rows) {
      const columns = Object.keys(row);
      const values = columns.map((col) => {
        const val = row[col];
        if (val === null) return "NULL";
        if (typeof val === "number") return String(val);
        if (typeof val === "boolean") return val ? "TRUE" : "FALSE";
        return `'${String(val).replace(/'/g, "''")}'`;
      });
      lines.push(
        `INSERT INTO ${table.name} (${columns.join(", ")}) VALUES (${values.join(", ")}) ON CONFLICT DO NOTHING;`
      );
    }
    lines.push("");
  }

  lines.push("COMMIT;");
  return lines.join("\n");
}

async function pushToGitHub(
  token: string,
  repo: string,
  files: Map<string, string>,
  commitMessage: string
): Promise<string> {
  const baseUrl = `https://api.github.com/repos/${repo}`;
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
  };

  // Get the current commit SHA for main
  const refRes = await fetch(`${baseUrl}/git/ref/heads/main`, { headers });
  if (!refRes.ok) throw new Error(`Failed to get ref: ${await refRes.text()}`);
  const refData = await refRes.json();
  const parentSha = refData.object.sha;

  // Get the tree SHA of the parent commit
  const commitRes = await fetch(`${baseUrl}/git/commits/${parentSha}`, { headers });
  if (!commitRes.ok) throw new Error(`Failed to get commit: ${await commitRes.text()}`);
  const commitData = await commitRes.json();
  const baseTreeSha = commitData.tree.sha;

  // Create blobs for each file
  const treeItems: { path: string; mode: string; type: string; sha: string }[] = [];
  for (const [path, content] of files) {
    const blobRes = await fetch(`${baseUrl}/git/blobs`, {
      method: "POST",
      headers,
      body: JSON.stringify({ content: Buffer.from(content).toString("base64"), encoding: "base64" }),
    });
    if (!blobRes.ok) throw new Error(`Failed to create blob for ${path}: ${await blobRes.text()}`);
    const blobData = await blobRes.json();
    treeItems.push({ path, mode: "100644", type: "blob", sha: blobData.sha });
  }

  // Create a new tree
  const treeRes = await fetch(`${baseUrl}/git/trees`, {
    method: "POST",
    headers,
    body: JSON.stringify({ base_tree: baseTreeSha, tree: treeItems }),
  });
  if (!treeRes.ok) throw new Error(`Failed to create tree: ${await treeRes.text()}`);
  const treeData = await treeRes.json();

  // Create a new commit
  const newCommitRes = await fetch(`${baseUrl}/git/commits`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      message: commitMessage,
      tree: treeData.sha,
      parents: [parentSha],
    }),
  });
  if (!newCommitRes.ok) throw new Error(`Failed to create commit: ${await newCommitRes.text()}`);
  const newCommitData = await newCommitRes.json();

  // Update the reference
  const updateRefRes = await fetch(`${baseUrl}/git/refs/heads/main`, {
    method: "PATCH",
    headers,
    body: JSON.stringify({ sha: newCommitData.sha }),
  });
  if (!updateRefRes.ok) throw new Error(`Failed to update ref: ${await updateRefRes.text()}`);

  return newCommitData.sha;
}

export default async function handler(req: Request): Promise<Response> {
  // Auth check
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) {
    return new Response(JSON.stringify({ error: "CRON_SECRET not configured" }), { status: 500 });
  }

  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${cronSecret}`) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401 });
  }

  // Env checks
  const supabaseUrl = process.env.VITE_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const githubToken = process.env.BACKUP_GITHUB_TOKEN;
  const backupRepo = process.env.BACKUP_REPO;

  if (!supabaseUrl || !supabaseKey) {
    return new Response(JSON.stringify({ error: "Missing Supabase env vars" }), { status: 500 });
  }
  if (!githubToken || !backupRepo) {
    return new Response(JSON.stringify({ error: "Missing GitHub backup env vars" }), { status: 500 });
  }

  const supabase = createClient(supabaseUrl, supabaseKey);

  try {
    const tableData = new Map<string, Record<string, unknown>[]>();
    const counts: Record<string, number> = {};
    let totalRows = 0;

    // Fetch all tables
    for (const table of TABLES) {
      const { rows, count } = await fetchAllRows(supabase, table);
      tableData.set(table.name, rows);
      counts[table.name] = count;
      totalRows += count;
    }

    // Generate files
    const files = new Map<string, string>();
    const now = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");

    for (const [tableName, rows] of tableData) {
      files.set(`data/${tableName}.json`, JSON.stringify(rows, null, 2));
    }

    files.set("restore.sql", generateRestoreSql(tableData));

    const manifest = {
      timestamp: now,
      tables: counts,
      totalRows,
    };
    files.set("manifest.json", JSON.stringify(manifest, null, 2));

    // Build commit message
    const countSummary = Object.entries(counts)
      .map(([t, c]) => `${t}: ${c}`)
      .join(", ");
    const commitMessage = `Backup ${now} \u2014 ${totalRows} rows (${countSummary})`;

    // Push to GitHub
    const commitSha = await pushToGitHub(githubToken, backupRepo, files, commitMessage);

    return new Response(
      JSON.stringify({ success: true, commit: commitSha, totalRows, tables: counts }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return new Response(JSON.stringify({ error: message }), { status: 500 });
  }
}
